# kafka를 실행하기 위한 파일.
# Cassandara + Zoopkeeper + Kafka 함께 실행.
# (Kafka를 실행하려면 Zoopkeeper를 실행해야 함.)

version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra_network_traffic
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_network_traffic
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_network_traffic
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
